name: Test Si example

on:
  push:
    branches:
      - develop
    # paths:
    #   - '**.cpp'
    #   - '**.h'
    #   - '**.py'
    #   - '**.c'
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
#        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ['3.10']
    name: OS ${{ matrix.os }} Python ${{ matrix.python-version }} 
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: alamode
          python-version: ${{ matrix.python-version }}
     
      - name: Get Date
        id: get-date
        run: echo "::set-output name=today::$(/bin/date -u '+%Y%m%d')"
        shell: bash
        
      - name: Cache Conda env
        uses: actions/cache@v4
        env:
          # Increase this value to reset cache if etc/alm-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-${{ runner.os }}--${{ runner.arch }}--${{ steps.get-date.outputs.today }}-${{ hashFiles('etc/alamode-environment.yml') }}-${{ env.CACHE_NUMBER }}
        id: cache
         
      - name: Update environment
        run: conda env update -n anaconda-client-env -f etc/alamode-environment.yml
        if: steps.cache.outputs.cache-hit != 'true'
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - name: Install conda libraries
        run: conda install numpy scipy h5py compilers spglib boost eigen cmake openmpi fftw
        
      - run: echo ${CC} ${CXX}

      - name: Build alm and anphon with cmake
        run: |
          mkdir -p _build
          cd _build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j
          cd ..
      
      - name: Run test Si
        working-directory: ./test
        run: python test_si.py
